Feature/chapter 9
gabrieladutra/JavaExercises pull request #5
Opened 2020-08-07 02:13 UTC by gabrieladutra

2020-08-15 17:52 UTC, SerenityInAllThings commented on src/main/java/src/chapter9/Examples.java
> +  public static void print2D(int[][] mat) {
Great printing tool! Congratulations!

2020-08-15 18:09 UTC, SerenityInAllThings requested changes
Some files modified/added in this branch are not related to chapter 9.
Question 4 is missing tests.
Questions 5-12 are missing.
Some adjustments required.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter4/question1/Bird.java
>  package src.chapter4.question1;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter4/question2/Bird.java
> +package src.chapter4.question2;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter4/question2/TestClass.java
> +
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter4/question3/Bird.java
> +package src.chapter4.question3;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter4/question3/TestClass.java
> +package src.chapter4.question3;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter4/question4/Bird.java
> +package src.chapter4.question4;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter5/question1/Question1.java
> +package src.chapter5.question1;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter5/question2/Question2.java
> +package src.chapter5.question2;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter5/question3/Question3.java
> +package src.chapter5.question3;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter5/question4/Question4.java
> +package src.chapter5.question4;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/main/java/src/chapter9/question2/Question2.java
> +    public static void printArrayElement(int[] paramArray){
Change element to plural.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/test/java/chapter4/Question2Test.java
> +package chapter4;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/test/java/chapter5/Question1Test.java
> +package chapter5;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/test/java/chapter5/Question2Test.java
> +package chapter5;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/test/java/chapter5/Question3Test.java
> +package chapter5;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/test/java/chapter5/Question4Test.java
> +package chapter5;
Delete this file from this branch.

2020-08-15 18:09 UTC, SerenityInAllThings commented on src/test/java/chapter7/Question2Test.java
> +package chapter7;
Delete this file from this branch.

2020-09-22 18:40 UTC, gabrieladutra commented on src/main/java/src/chapter4/question1/Bird.java
>  package src.chapter4.question1;
File deleted.

2020-09-22 18:40 UTC, gabrieladutra commented on src/main/java/src/chapter4/question2/Bird.java
> +package src.chapter4.question2;
File deleted.

2020-09-22 18:40 UTC, gabrieladutra commented on src/main/java/src/chapter4/question3/TestClass.java
> +package src.chapter4.question3;
File deleted.

2020-09-22 18:40 UTC, gabrieladutra commented on src/main/java/src/chapter4/question3/Bird.java
> +package src.chapter4.question3;
File deleted.

2020-09-22 18:40 UTC, gabrieladutra commented on src/main/java/src/chapter4/question4/Bird.java
> +package src.chapter4.question4;
File deleted.

2020-09-22 18:41 UTC, gabrieladutra commented on src/test/java/chapter5/Question1Test.java
> +package chapter5;
File deleted.

2020-09-22 18:41 UTC, gabrieladutra commented on src/main/java/src/chapter5/question1/Question1.java
> +package src.chapter5.question1;
File deleted.

2020-09-22 18:41 UTC, gabrieladutra commented on src/main/java/src/chapter5/question4/Question4.java
> +package src.chapter5.question4;
File deleted.

2020-09-22 18:41 UTC, gabrieladutra commented on src/test/java/chapter4/Question2Test.java
> +package chapter4;
File deleted.

2020-09-22 18:41 UTC, gabrieladutra commented on src/test/java/chapter5/Question3Test.java
> +package chapter5;
File deleted.

2020-09-22 18:42 UTC, gabrieladutra commented on src/test/java/chapter7/Question2Test.java
> +package chapter7;
File deleted.

2020-09-22 18:42 UTC, gabrieladutra commented on src/test/java/chapter5/Question4Test.java
> +package chapter5;
File deleted.

2020-09-22 18:42 UTC, gabrieladutra commented on src/test/java/chapter5/Question2Test.java
> +package chapter5;
File deleted.

2020-09-22 18:43 UTC, gabrieladutra commented on src/main/java/src/chapter9/question2/Question2.java
> +    public static void printArrayElement(int[] paramArray){
Fixed

2020-09-22 18:49 UTC, gabrieladutra commented on src/main/java/src/chapter9/Examples.java
> +  public static void print2D(int[][] mat) {
Thank you!

2020-09-22 18:50 UTC, gabrieladutra commented on src/main/java/src/chapter4/question2/TestClass.java
> +
File deleted.

2020-09-22 18:53 UTC, merged